#mariaDB 
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: meow
    password: 1234
    url: jdbc:mariadb://localhost:3306/meow
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  thymeleaf:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    #Auto Restart : 자동으로 서버 재기동 기능
    restart:
      enabled: true
    #리소스 변경 시 새로고침하는 트리거
    livereload:
      enabled: true
server:
  port: 8080
