
#mariaDB 
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: meow
    password: 1234
    url: jdbc:mariadb://localhost:3306/meow
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  thymeleaf:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080